version: '0.0.1'
source: "C:/Users/tr7zw/workspace/ForgeFabricComposeTemplate"
replacements:
  group: "dev.tr7zw"
  name: "ItemSwapper"
  id: "itemswapper"
  version: "1.0.0"
  author: "tr7zw"
  dependencies: ""
  licensename: "LICENSE"
rootProject:
  template: "."
subProjects:
  XTFabric:
    template: "Fabric"