version: '0.0.1'
source: "https://github.com/tr7zw/ForgeFabricComposeTemplate/tree/1.19.2/"
replacements:
  group: "dev.tr7zw"
  name: "ItemSwapper"
  id: "itemswapper"
  version: "0.1.0"
  author: "tr7zw"
  dependencies: ""
  relocationpackage: "dev.tr7zw.itemswapper"
  licensename: "LICENSE"
rootProject:
  template: "."
subProjects:
  XTFabric:
    template: "Fabric"